---
config:
  theme: 'forest'
---
mindmap
  root((Hoteles Vitae))
    Sedes
        Galery
        Galerias
        Corferias
    EPS afiliadas
        Salud total
        Famisanar
        Nueva EPS
        Sura
        Sanitas
        Colombiana<br/>de transplantes
        Contraminas
        Policia nacional
    Servicios
        Albergue
        Alimentación
        Transporte
    Personal
        Adminstradores
        Reservas
        Coordinador de ruta
        Facturación